version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/con-tracker-admin"
    target-branch: "dev"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/con-tracker-api"
    target-branch: "dev"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/con-tracker-client"
    target-branch: "dev"
    schedule:
      interval: "daily"
